quarkus:
  devservices:
    enabled: false

  swagger-ui:
    always-include: true

  http:
    root-path: /${project.artifactId}
    port: 3000

  application:
    name: @project.artifactId@ # nome da aplicação será usando para definir o repositório de configura para o config-server

  log:
    console:
      json: false
      format: '%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n'
    min-level: DEBUG

  spring-cloud-config:
    enabled: true # conexão com o config-server está disabilitado por padrão
    url: https://api-java-qa.repassa.net.br/backoffice-spring-config/

s3:
  aws:
    access-key: AKIAJWITEVM4HXREFLYA
    secret-key: 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
    region: us-east-1
    bucket-name: backoffice-triage-photo-stg
    url-base: https://${s3.aws.bucket-name}.s3.amazonaws.com
    error-image: ${s3.aws.url-base}/invalidPhoto.png
    front-url: https://assets-qa-curadoria.repassa.com.br
dynamo:
  table:
    photoProcessing: PhotoProcessingTable_QA
    photosManager: PhotosManager_QA