quarkus:
  devservices:
    enabled: false

  swagger-ui:
    always-include: true

#  spring-cloud-config:
#    enabled: true # conexão com o config-server está disabilitado por padrão
#    url: https://api-java-dev.repassa.net.br/backoffice-spring-config/